#!/bin/sh
set -eu

ROOT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
. "$ROOT_DIR/tests/lib/assert.sh"

WORK_DIR="$ROOT_DIR/tests/tmp/core_tools"
rm -rf "$WORK_DIR"
mkdir -p "$WORK_DIR/src/sub" "$WORK_DIR/grepdir/nested" "$WORK_DIR/lsdir/sub" "$WORK_DIR/finddir/sub"

note "core tools"

printf 'alpha\n' > "$WORK_DIR/src/root.txt"
printf 'beta\n' > "$WORK_DIR/src/sub/file.txt"
assert_command_succeeds "$ROOT_DIR/build/cp" -r "$WORK_DIR/src" "$WORK_DIR/dest"
assert_file_contains "$WORK_DIR/dest/sub/file.txt" beta "cp recursive copy failed"

printf 'Hello\nworld\nHELLO\n' > "$WORK_DIR/grepdir/a.txt"
printf 'hello nested\nskip me\n' > "$WORK_DIR/grepdir/nested/b.txt"
"$ROOT_DIR/build/grep" -ir hello "$WORK_DIR/grepdir" > "$WORK_DIR/grep.out"
assert_file_contains "$WORK_DIR/grep.out" 'a.txt:Hello' "grep recursive ignore-case failed"
assert_file_contains "$WORK_DIR/grep.out" 'b.txt:hello nested' "grep recursive nested match missing"
"$ROOT_DIR/build/grep" -v skip "$WORK_DIR/grepdir/nested/b.txt" > "$WORK_DIR/grep_v.out"
assert_file_contains "$WORK_DIR/grep_v.out" 'hello nested' "grep invert-match failed"
printf 'Äpfel\nöl\n' > "$WORK_DIR/grep_unicode.txt"
"$ROOT_DIR/build/grep" -i -F 'äpfel' "$WORK_DIR/grep_unicode.txt" > "$WORK_DIR/grep_unicode.out"
assert_file_contains "$WORK_DIR/grep_unicode.out" '^Äpfel$' "grep Unicode ignore-case fixed-string matching failed"

printf '123456\n' > "$WORK_DIR/lsdir/large"
printf '1\n' > "$WORK_DIR/lsdir/small"
touch -t 202401010101 "$WORK_DIR/lsdir/small"
touch -t 202501010101 "$WORK_DIR/lsdir/large"
"$ROOT_DIR/build/ls" -R "$WORK_DIR/lsdir" > "$WORK_DIR/ls_r.out"
assert_file_contains "$WORK_DIR/ls_r.out" 'lsdir/sub:' "ls recursive listing failed"
"$ROOT_DIR/build/ls" -S "$WORK_DIR/lsdir" > "$WORK_DIR/ls_s.out"
assert_file_contains "$WORK_DIR/ls_s.out" '^large$' "ls size ordering missing"
mkdir -p "$WORK_DIR/lsrev"
printf 'a\n' > "$WORK_DIR/lsrev/a"
printf 'b\n' > "$WORK_DIR/lsrev/b"
printf 'c\n' > "$WORK_DIR/lsrev/c"
mkdir -p "$WORK_DIR/lsrev/dironly"
"$ROOT_DIR/build/ls" -r "$WORK_DIR/lsrev" > "$WORK_DIR/ls_rev.out"
rev_first=$(head -n 1 "$WORK_DIR/ls_rev.out" | tr -d '\r\n')
assert_text_equals "$rev_first" 'dironly' "ls reverse ordering failed"
"$ROOT_DIR/build/ls" -1F "$WORK_DIR/lsrev" > "$WORK_DIR/ls_flags.out"
assert_file_contains "$WORK_DIR/ls_flags.out" '^dironly/$' "ls classification flag missing directory suffix"

printf '10\n2\n2\n1\n' > "$WORK_DIR/sort.txt"
"$ROOT_DIR/build/sort" -nru "$WORK_DIR/sort.txt" > "$WORK_DIR/sort.out"
printf '10\n2\n1\n' > "$WORK_DIR/sort.expected"
assert_files_equal "$WORK_DIR/sort.out" "$WORK_DIR/sort.expected" "sort numeric reverse unique failed"

printf 'abc\n' > "$WORK_DIR/finddir/small.txt"
printf 'abcdef\n' > "$WORK_DIR/finddir/big.txt"
"$ROOT_DIR/build/find" "$WORK_DIR/finddir" -type f -size +3c > "$WORK_DIR/find_size.out"
assert_file_contains "$WORK_DIR/find_size.out" 'big.txt' "find size filter failed"

printf 'foo\nfoo\nfoo\n' > "$WORK_DIR/sed.txt"
printf '2s/foo/BAR/\n' > "$WORK_DIR/script.sed"
"$ROOT_DIR/build/sed" -f "$WORK_DIR/script.sed" "$WORK_DIR/sed.txt" > "$WORK_DIR/sed.out"
printf 'foo\nBAR\nfoo\n' > "$WORK_DIR/sed.expected"
assert_files_equal "$WORK_DIR/sed.out" "$WORK_DIR/sed.expected" "sed addressed script failed"

printf '界界\n' > "$WORK_DIR/unicode_width.txt"
"$ROOT_DIR/build/wc" -L "$WORK_DIR/unicode_width.txt" > "$WORK_DIR/unicode_width.out"
unicode_width=$(awk '{print $1}' "$WORK_DIR/unicode_width.out" | tr -d '\r\n ')
assert_text_equals "$unicode_width" '4' "wc did not account for wide Unicode characters in line width"
printf 'äö🙂\n' > "$WORK_DIR/unicode_rev.txt"
"$ROOT_DIR/build/rev" "$WORK_DIR/unicode_rev.txt" > "$WORK_DIR/unicode_rev.out"
assert_file_contains "$WORK_DIR/unicode_rev.out" '^🙂öä$' "rev did not preserve UTF-8 characters while reversing"
printf '界 a\nxx bb\n' > "$WORK_DIR/column_unicode.txt"
"$ROOT_DIR/build/column" -t "$WORK_DIR/column_unicode.txt" > "$WORK_DIR/column_unicode.out"
assert_file_contains "$WORK_DIR/column_unicode.out" '^界  a$' "column did not align wide Unicode cells correctly"
assert_file_contains "$WORK_DIR/column_unicode.out" '^xx  bb$' "column did not preserve aligned output for ASCII rows"
printf '界界界a\n' > "$WORK_DIR/fold_unicode.txt"
"$ROOT_DIR/build/fold" -w 6 "$WORK_DIR/fold_unicode.txt" > "$WORK_DIR/fold_unicode.out"
assert_file_contains "$WORK_DIR/fold_unicode.out" '^界界界$' "fold did not wrap on Unicode display width boundaries"
assert_file_contains "$WORK_DIR/fold_unicode.out" '^a$' "fold did not preserve the trailing character after Unicode wrapping"
printf 'äö aa\n' > "$WORK_DIR/fmt_unicode.txt"
"$ROOT_DIR/build/fmt" -w 5 "$WORK_DIR/fmt_unicode.txt" > "$WORK_DIR/fmt_unicode.out"
assert_file_contains "$WORK_DIR/fmt_unicode.out" '^äö aa$' "fmt did not keep a Unicode-width-fitting line intact"
