command=./build/httpd -c services/httpd/config/httpd.conf
pidfile=services/httpd/log/httpd.pid
stdout=services/httpd/log/httpd.log
stderr=services/httpd/log/httpd.log
workdir=.
# user=www
# group=www
stop_timeout=3s
