#!/usr/bin/env python3
"""Build the experimental freestanding multicall binary."""

import concurrent.futures
import os
import re
import shlex
import subprocess
import sys
from pathlib import Path


ROOT = Path(os.environ.get("ROOT", ".")).resolve()
OUTPUT = Path(os.environ["OUTPUT"]).resolve()
OBJDIR = Path(os.environ["OBJDIR"]).resolve()
SYMLINK_DIR = Path(os.environ["SYMLINK_DIR"]).resolve()
TOOLS = shlex.split(os.environ["TOOLS"])
SUPPORT_SOURCES = shlex.split(os.environ.get("SUPPORT_SOURCES", ""))
TARGET_CRT = os.environ["TARGET_CRT"]
CC = shlex.split(os.environ["TARGET_CC"])
TARGET_FLAG = shlex.split(os.environ.get("TARGET_CC_TARGET_FLAG", ""))
CFLAGS = shlex.split(os.environ.get("MULTICALL_CFLAGS", ""))
LDFLAGS = shlex.split(os.environ.get("MULTICALL_LDFLAGS", ""))
JOBS = max(1, int(os.environ.get("MULTICALL_JOBS", "1")))
ALIASES = {
    "ping6": "ping",
    "rg": "ripgrep",
}


def rel(path):
    return str(Path(path))


def source_path(path):
    return ROOT / path


def sanitize_tool_name(name):
    if name == "[":
        return "lbracket"
    out = []
    for ch in name:
        if ("a" <= ch <= "z") or ("A" <= ch <= "Z") or ("0" <= ch <= "9") or ch == "_":
            out.append(ch)
        else:
            out.append("_u%02x" % ord(ch))
    text = "".join(out)
    if not text or text[0].isdigit():
        text = "tool_" + text
    return text


def has_void_main(path):
    data = source_path(path).read_text(encoding="utf-8")
    return re.search(r"\bint\s+main\s*\(\s*void\s*\)", data) is not None


def run_command(cmd, label):
    result = subprocess.run(cmd, cwd=ROOT, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if result.returncode != 0:
        sys.stderr.write("%s failed\n" % label)
        if result.stdout:
            sys.stderr.write(result.stdout)
        if result.stderr:
            sys.stderr.write(result.stderr)
        raise SystemExit(result.returncode)


def compile_one(source, obj, extra_flags):
    obj.parent.mkdir(parents=True, exist_ok=True)
    cmd = CC + TARGET_FLAG + CFLAGS + extra_flags + ["-c", rel(source), "-o", str(obj)]
    result = subprocess.run(cmd, cwd=ROOT, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if result.returncode != 0:
        return result.returncode, source, result.stdout, result.stderr
    return 0, source, result.stdout, result.stderr


def unique_paths(paths):
    seen = set()
    out = []
    for path in paths:
        if not path:
            continue
        if path in seen:
            continue
        seen.add(path)
        out.append(path)
    return out


def generate_dispatcher(path, dispatch_entries):
    lines = [
        "/* Generated by experimental/multicall/build.py. */",
        '#include "runtime.h"',
        "",
        "typedef int (*MulticallMain)(int argc, char **argv);",
        "",
        "typedef struct {",
        "    const char *name;",
        "    MulticallMain main;",
        "} MulticallApplet;",
        "",
    ]

    for entry in dispatch_entries:
        symbol = entry["symbol"]
        if entry["void_main"]:
            lines.append("int %s(void);" % symbol)
            lines.append("static int call_%s(int argc, char **argv) {" % entry["identifier"])
            lines.append("    (void)argc;")
            lines.append("    (void)argv;")
            lines.append("    return %s();" % symbol)
            lines.append("}")
        else:
            lines.append("int %s(int argc, char **argv);" % symbol)
            if entry["alias_of"] is not None:
                lines.append("static int call_%s(int argc, char **argv) {" % entry["identifier"])
                lines.append("    return %s(argc, argv);" % symbol)
                lines.append("}")
        lines.append("")

    lines.extend([
        "static const char *multicall_basename(const char *path) {",
        "    const char *base = path;",
        "    size_t index = 0U;",
        "",
        "    while (path[index] != '\\0') {",
        "        if (path[index] == '/') {",
        "            base = path + index + 1U;",
        "        }",
        "        index += 1U;",
        "    }",
        "    return base;",
        "}",
        "",
        "static int multicall_streq(const char *left, const char *right) {",
        "    while (*left != '\\0' && *right != '\\0') {",
        "        if (*left != *right) {",
        "            return 0;",
        "        }",
        "        left += 1;",
        "        right += 1;",
        "    }",
        "    return *left == '\\0' && *right == '\\0';",
        "}",
        "",
        "static const MulticallApplet multicall_applets[] = {",
    ])

    for entry in dispatch_entries:
        target = "call_%s" % entry["identifier"] if entry["void_main"] or entry["alias_of"] is not None else entry["symbol"]
        lines.append('    { "%s", %s },' % (entry["name"].replace("\\", "\\\\").replace('"', '\\"'), target))
    lines.extend([
        "};",
        "",
        "static const MulticallApplet *multicall_find(const char *name) {",
        "    size_t index = 0U;",
        "",
        "    while (index < sizeof(multicall_applets) / sizeof(multicall_applets[0])) {",
        "        if (multicall_streq(name, multicall_applets[index].name)) {",
        "            return multicall_applets + index;",
        "        }",
        "        index += 1U;",
        "    }",
        "    return 0;",
        "}",
        "",
        "static void multicall_usage(void) {",
        '    rt_write_line(2, "usage: multicall TOOL [ARGS...]");',
        '    rt_write_line(2, "       or invoke through a symlink named after a tool");',
        '    rt_write_cstr(2, "tools:");',
        "    for (size_t index = 0U; index < sizeof(multicall_applets) / sizeof(multicall_applets[0]); index += 1U) {",
        "        rt_write_char(2, ' ');",
        "        rt_write_cstr(2, multicall_applets[index].name);",
        "    }",
        "    rt_write_char(2, '\\n');",
        "}",
        "",
        "int main(int argc, char **argv) {",
        "    const MulticallApplet *applet;",
        "    const char *name;",
        "",
        "    if (argc <= 0 || argv == 0 || argv[0] == 0) {",
        "        multicall_usage();",
        "        return 1;",
        "    }",
        "",
        "    name = multicall_basename(argv[0]);",
        "    applet = multicall_find(name);",
        "    if (applet != 0) {",
        "        return applet->main(argc, argv);",
        "    }",
        "",
        "    if (argc >= 2) {",
        "        applet = multicall_find(argv[1]);",
        "        if (applet != 0) {",
        "            return applet->main(argc - 1, argv + 1);",
        "        }",
        "        rt_write_cstr(2, \"multicall: unknown tool: \");",
        "        rt_write_line(2, argv[1]);",
        "    } else {",
        "        multicall_usage();",
        "    }",
        "    return 1;",
        "}",
        "",
    ])
    path.write_text("\n".join(lines), encoding="utf-8")


def create_symlinks():
    SYMLINK_DIR.mkdir(parents=True, exist_ok=True)
    rel_target = os.path.relpath(OUTPUT, SYMLINK_DIR)
    for tool in TOOLS:
        link = SYMLINK_DIR / tool
        try:
            if link.is_symlink() or link.exists():
                link.unlink()
            link.symlink_to(rel_target)
        except OSError:
            pass


def main():
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OBJDIR.mkdir(parents=True, exist_ok=True)

    dispatch_entries = []
    compile_tasks = []
    compiled_tools = {}

    for tool in TOOLS:
        if tool in ALIASES:
            continue
        identifier = sanitize_tool_name(tool)
        source = "src/tools/%s.c" % tool
        symbol = "multicall_%s_main" % identifier
        compiled_tools[tool] = symbol
        dispatch_entries.append({
            "name": tool,
            "identifier": identifier,
            "symbol": symbol,
            "void_main": has_void_main(source),
            "alias_of": None,
        })
        compile_tasks.append((source, OBJDIR / "tools" / ("%s.o" % identifier), ["-Dmain=%s" % symbol]))

    for alias, target in ALIASES.items():
        if alias not in TOOLS:
            continue
        symbol = compiled_tools[target]
        dispatch_entries.append({
            "name": alias,
            "identifier": sanitize_tool_name(alias),
            "symbol": symbol,
            "void_main": False,
            "alias_of": target,
        })

    generated_c = OBJDIR / "multicall_dispatch.c"
    generate_dispatcher(generated_c, sorted(dispatch_entries, key=lambda entry: entry["name"]))
    compile_tasks.append((str(generated_c), OBJDIR / "multicall_dispatch.o", []))

    support_sources = unique_paths(SUPPORT_SOURCES + [TARGET_CRT])
    for source in support_sources:
        source_obj = OBJDIR / "support" / (source.replace("/", "__").replace(".", "_") + ".o")
        compile_tasks.append((source, source_obj, []))

    objects = [str(task[1]) for task in compile_tasks]
    with concurrent.futures.ThreadPoolExecutor(max_workers=JOBS) as pool:
        futures = [pool.submit(compile_one, source, obj, flags) for source, obj, flags in compile_tasks]
        for future in concurrent.futures.as_completed(futures):
            returncode, source, stdout, stderr = future.result()
            if returncode != 0:
                sys.stderr.write("%s failed\n" % source)
                if stdout:
                    sys.stderr.write(stdout)
                if stderr:
                    sys.stderr.write(stderr)
                raise SystemExit(returncode)

    run_command(CC + TARGET_FLAG + objects + LDFLAGS + ["-o", str(OUTPUT)], "link")
    create_symlinks()
    print("built %s (%d applets)" % (OUTPUT, len(dispatch_entries)))


if __name__ == "__main__":
    main()
